// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"log"
	"net/http"
	"os"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/openconfig/catalog-server/graph"
	"github.com/openconfig/catalog-server/graph/generated"
	"github.com/openconfig/catalog-server/pkg/db"
)

const defaultPort = "8080" // default port of launched catalog server

// Main function is automatically generated by *gqlgen*, except ConnectDB() to connect to database.
func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = defaultPort
	}

	// Establish connection with database, other codes are automatically generated.
	err := db.ConnectDB()
	if err != nil {
		log.Fatal(err)
	}

	srv := handler.NewDefaultServer(generated.NewExecutableSchema(generated.Config{Resolvers: &graph.Resolver{}}))

	// Launch built-in graphQL frontend server.
	http.Handle("/", playground.Handler("GraphQL playground", "/query"))
	// Set handler for all queries.
	http.Handle("/query", srv)

	// static file server to serve frontend webpages.
	fileServer := http.FileServer(http.Dir("frontend"))
	http.HandleFunc(
		"/static/",
		func(w http.ResponseWriter, r *http.Request) {
			fileServer.ServeHTTP(w, r)
		},
	)

	log.Printf("connect to http://localhost:%s/ for GraphQL playground", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}
