// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Module struct {
	OrgName string `json:"OrgName"`
	Name    string `json:"Name"`
	Version string `json:"Version"`
	Data    string `json:"Data"`
}
